vrindavan_project/logsign/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

urlpatterns = [

    
    path('login/', Login,name="adminlogin"),
    path('signup/', register, name="adminregister"),\
    path('admin-dashboard/', admin_dashboard,name="admin_dashboard"),
    path('logout/', Logout, name='userlogout')
   

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vrindavan_project/vrindavan_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('userpage.urls')),
    path('mycard/', include('digitalcard.urls')),
    path('account/', include('logsign.urls')),
    path('admin-dashboard/', include('adminpage.urls')),
    path('password_reset/', include('resetpassword.urls')),
    path('', Home, name='user_dashboard'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vrindavan_project/userpage/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
   cat_name = models.CharField(max_length=200)

   def __str__(self):
        return self.cat_name

class Products(models.Model):
    name = models.CharField(max_length=1000)
    image = models.ImageField(upload_to='product/image')
    description = models.TextField(max_length=50)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, related_name="products")

    def __str__(self):
     return self.name

vrindavan_project/templates/adminfile/about-us-content.html
{% extends 'adminfile/ad_parent.html' %}
{% block contents %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Edit Restaurant Info</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <div class="container">
      <h2>Edit Restaurant Information</h2>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save Changes</button>
      </form>
      <a href="{% url 'admin_dashboard' %}" class="btn btn-secondary mt-3">Cancel</a> <!-- Replace with the correct URL name -->
    </div>
  </body>
</html>


{% endblock %}

vrindavan_project/templates/adminfile/ad_parent.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto:400,700"
    />
    <!-- https://fonts.google.com/specimen/Roboto -->
    <link
      rel="stylesheet"
      href="{% static 'adminfiles/css/fontawesome.min.css' %}"
    />
    <!-- https://fontawesome.com/ -->
    <link
      rel="stylesheet"
      href="{% static 'adminfiles/css/bootstrap.min.css' %}"
    />
    <!-- https://getbootstrap.com/ -->
    <link
      rel="stylesheet"
      href="{% static 'adminfiles/css/templatemo-style.css' %}"
    />
    <!--
	Product Admin CSS Template
	https://templatemo.com/tm-524-product-admin
	-->
  </head>

  <body id="reportsPage">
    <div class="" id="home">
      <nav class="navbar navbar-expand-xl">
        <div class="container h-100">
          <a
            class="navbar-brand"
            href="{% static 'adminfile/dashboard.html' %}"
          >
            <h1 class="tm-site-title mb-0">{{request.user.username}}</h1>
          </a>
          <button
            class="navbar-toggler ml-auto mr-0"
            type="button"
            data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <i class="fas fa-bars tm-nav-icon"></i>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto h-100">
              <li class="nav-item">
                <a
                  class="nav-link {{dashboard_admin}}"
                  href="{% url 'admin_dashboard' %}"
                >
                  <i class="fas fa-tachometer-alt"></i>
                  Dashboard
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'userlist' %}">
                  <i class="far fa-user"></i> Accounts
                </a>
              </li>
              <li class="nav-item">
                <a
                  class="nav-link {{product_admin}}"
                  href="{% url 'admin_product' %}"
                >
                  <i class="fas fa-shopping-cart"></i>
                  Products
                </a>
              </li>
            </ul>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link d-block" href="{% url 'userlogout' %}">
                  <h5>Logout</h5>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      {% block contents %} {% endblock %}

      <footer class="tm-footer row tm-mt-small">
        <div class="col-12 font-weight-light">
          <p class="text-center text-white mb-0 px-4 small">
            Copyright &copy; <b>2018</b> All rights reserved. Design:
            <a
              rel="nofollow noopener"
              href="https://templatemo.com"
              class="tm-footer-link"
              >Template Mo</a
            >
          </p>
        </div>
      </footer>
    </div>

    <script src="{% static 'adminfiles/js/moment.min.js' %}"></script>
    <!-- https://momentjs.com/ -->
    <script src="{% static 'adminfiles/js/Chart.min.js' %}"></script>
    <!-- http://www.chartjs.org/docs/latest/ -->
    <script src="{% static 'adminfiles/js/tooplate-scripts.js' %}"></script>
    <script>
      Chart.defaults.global.defaultFontColor = "white";
      let ctxLine,
        ctxBar,
        ctxPie,
        optionsLine,
        optionsBar,
        optionsPie,
        configLine,
        configBar,
        configPie,
        lineChart;
      barChart, pieChart;
      // DOM is ready
      $(function () {
        drawLineChart(); // Line Chart
        drawBarChart(); // Bar Chart
        drawPieChart(); // Pie Chart

        $(window).resize(function () {
          updateLineChart();
          updateBarChart();
        });
      });
    </script>
  </body>
</html>

vrindavan_project/templates/adminfile/add-category.html
{% extends 'adminfile/ad_parent.html' %}
{% load static %}




{% block contents %}


<div class="col-sm-12 col-md-12 col-lg-4 col-xl-4 tm-block-col">
    <div class="tm-bg-primary-dark tm-block tm-block-product-categories">
      <h2 class="tm-block-title">Add Categories</h2>
      <div class="tm-product-table-container">
        <table class="table tm-table-small tm-product-table">
          <tbody>
           
            <tr>
              <td class="tm-product-name">
                <form method="post" >
                {% csrf_token %}
                {{ form.as_p }}</td>
              
            </tr>

          </tbody>
        </table>
      </div>
      <button type="submit" class="btn btn-primary btn-block text-uppercase mb-3">Add Category</button>
    </form>
    </div>
  </div>


{% endblock %}

vrindavan_project/templates/adminfile/add-product.html
{% extends 'adminfile/ad_parent.html' %}
{% load static %}

{% block contents %}

<title>Add Product - Dashboard HTML Template</title>

<link rel="stylesheet" href="jquery-ui-datepicker/jquery-ui.min.css" type="text/css" />
<!-- http://api.jqueryui.com/datepicker/ -->


<div class="container tm-mt-big tm-mb-big">
  <div class="row">
      <div class="col-xl-9 col-lg-10 col-md-12 col-sm-12 mx-auto">
          <div class="tm-bg-primary-dark tm-block tm-block-h-auto">
              <div class="row">
                  <div class="col-12">
                      <h2 class="tm-block-title d-inline-block">Add Product</h2>
                  </div>
              </div>
              <div class="row tm-edit-product-row">
                  <div class="col-xl-6 col-lg-6 col-md-12">
                      <form action="{% url 'product_form' %}" class="tm-edit-product-form" method="post" enctype="multipart/form-data">
                          {% csrf_token %}

                          {% if messages %}
                          {% for message in messages %}
                              <div class="alert alert-{{ message.tags }}">
                                  {{ message }}
                              </div>
                          {% endfor %}
                          {% endif %}

                          <div class="form-group mb-3">
                              <label for="id_name">Product Name</label>
                              {{ form.name }}
                          </div>
                          <div class="form-group mb-3">
                              <label for="id_description">Description</label>
                              {{ form.description }}
                          </div>
                          <div class="form-group mb-3">
                              <label for="id_category">Category</label>
                              {{ form.category }}
                          </div>
                          <div class="form-group mb-3">
                            <label for="id_category">Price</label>
                            {{ form.price }}
                          </div>
                          


                          <div class="form-group mb-3">
                            <label for="id_image">Image</label>
                            {{ form.image }}
                        </div>
                          <button type="submit" class="btn btn-primary btn-block text-uppercase">Add Product Now</button>
                          
                      </form>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>




<script src="jquery-ui-datepicker/jquery-ui.min.js"></script>
<!-- https://jqueryui.com/download/ -->

<script>
  $(function() {
    $("#expire_date").datepicker();
  });
</script>

{% endblock %}

vrindavan_project/templates/adminfile/add-team.html
{% extends 'adminfile/ad_parent.html' %}
{% load static %}

{% block contents %}

<title>Add Team members</title>

<link rel="stylesheet" href="jquery-ui-datepicker/jquery-ui.min.css" type="text/css" />
<!-- http://api.jqueryui.com/datepicker/ -->


<div class="container tm-mt-big tm-mb-big">
  <div class="row">
      <div class="col-xl-9 col-lg-10 col-md-12 col-sm-12 mx-auto">
          <div class="tm-bg-primary-dark tm-block tm-block-h-auto">
              <div class="row">
                  <div class="col-12">
                      <h2 class="tm-block-title d-inline-block">Add Product</h2>
                  </div>
              </div>
              <div class="row tm-edit-product-row">
                  <div class="col-xl-6 col-lg-6 col-md-12">
                      <form action="{% url 'team_form' %}" class="tm-edit-product-form" method="post" enctype="multipart/form-data">
                          {% csrf_token %}

                          {% if messages %}
                          {% for message in messages %}
                              <div class="alert alert-{{ message.tags }}">
                                  {{ message }}
                              </div>
                          {% endfor %}
                          {% endif %}

                          <div class="form-group mb-3">
                              <label for="id_name">Name</label>
                              {{ form.name }}
                          </div>
                          <div class="form-group mb-3">
                              <label for="id_description">Designation</label>
                              {{ form.designation }}
                          </div>
                          <div class="form-group mb-3">
                            <label for="id_image">Image</label>
                            {{ form.image }}
                        </div>
                          <button type="submit" class="btn btn-primary btn-block text-uppercase">Add Member</button>
                          
                      </form>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>




<script src="jquery-ui-datepicker/jquery-ui.min.js"></script>
<!-- https://jqueryui.com/download/ -->

<script>
  $(function() {
    $("#expire_date").datepicker();
  });
</script>

{% endblock %}

vrindavan_project/templates/adminfile/dashboard.html
{% extends 'adminfile/ad_parent.html' %} {% load static %} {% block contents %}

<title>Product Admin - Dashboard HTML Template</title>

<div class="container">
  <div class="row">
    <div class="col">
      <p class="text-white mt-5 mb-5">Welcome back, <b>Admin</b></p>
    </div>
  </div>
  <!-- row -->
  <div class="container mt-5">
    <div class="row tm-content-row">
      <div class="col-sm-12 col-md-12 col-lg-8 col-xl-8 tm-block-col">
        <div class="tm-bg-primary-dark tm-block tm-block-products">
          {% if messages %}
          <div id="message-container" class="alert alert-info">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
          </div>
          {% endif %}
          <div class="tm-product-table-container">
            <form
              id="team-form"
              method="POST"
              action="{% url 'delete_selected_teams' %}"
            >
              {% csrf_token %}
              <input type="hidden" name="is_multiple" value="true" />
              <table class="table table-hover tm-table-small tm-product-table">
                <thead>
                  <tr>
                    <th scope="col">&nbsp;</th>
                    <th scope="col">S.N.</th>
                    <th scope="col">Name</th>
                    <th scope="col">Designation</th>
                    <th scope="col"></th>
                    <th scope="col">&nbsp;</th>
                  </tr>
                </thead>
                <tbody>
                  {% for team in teamlist %}
                  <tr>
                    <th scope="row">
                      <input
                        type="checkbox"
                        name="selected_teams"
                        value="{{ team.id }}"
                      />
                    </th>
                    <td>{{ team.name }}</td>
                    <td>{{ team.designation }}</td>
                    <td>
                      <a
                        href="#"
                        class="tm-product-delete-link"
                        onclick="deleteSingleTeam({{ team.id }})"
                      >
                        <i class="far fa-trash-alt tm-product-delete-icon"></i>
                      </a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              <button
                type="button"
                class="btn btn-primary btn-block text-uppercase"
                onclick="deleteSelectedTeams()"
              >
                Delete selected members
              </button>
            </form>
          </div>
          <a
            href="{% url 'team_form' %}"
            class="btn btn-primary btn-block text-uppercase mb-3"
            >Add new member</a
          >
        </div>
      </div>
      <div class="col-sm-12 col-md-12 col-lg-4 col-xl-4 tm-block-col">
        <div class="tm-bg-primary-dark tm-block tm-block-product-categories">
          <h2 class="tm-block-title">Content Section</h2>
          <a
            href="{% url 'edit_restaurant_info' %}"
            class="btn btn-primary btn-block text-uppercase mb-3"
            >Edit Restaurant Info</a
          >
        </div>
      </div>
    </div>
  </div>

  <script src="{% static 'adminfiles/js/jquery-3.3.1.min.js' %}"></script>
  <!-- https://jquery.com/download/ -->
  <script src="{% static 'adminfiles/js/bootstrap.min.js' %}"></script>
  <!-- https://getbootstrap.com/ -->
  <script>
    function deleteSingleTeam(teamId) {
      if (confirm("Are you sure you want to delete this member?")) {
        const form = document.getElementById("team-form");
        form.action = `{% url 'delete_team' 0 %}`.replace("0", teamId);
        form.submit();
      }
    }

    function deleteSelectedTeams() {
      const form = document.getElementById("team-form");
      if (confirm("Are you sure you want to delete the selected member?")) {
        form.submit();
      }
    }
  </script>
</div>
{% endblock %}

vrindavan_project/templates/adminfile/edit-product.html
    {% extends 'adminfile/ad_parent.html' %}
    {% load static %}
    
    {% block contents %}
    
    <title>Edit Product - Dashboard Admin Template</title>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto:400,700"
    />
    <!-- https://fonts.google.com/specimen/Roboto -->

    <link rel="stylesheet" href="jquery-ui-datepicker/jquery-ui.min.css" type="text/css" />
    <!-- http://api.jqueryui.com/datepicker/ -->

 
    <nav class="navbar navbar-expand-xl">
      <div class="container h-100">
        <a class="navbar-brand" href="index.html">
          <h1 class="tm-site-title mb-0">Product Admin</h1>
        </a>
        <button
          class="navbar-toggler ml-auto mr-0"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars tm-nav-icon"></i>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mx-auto h-100">
            <li class="nav-item">
              <a class="nav-link" href="index.html">
                <i class="fas fa-tachometer-alt"></i> Dashboard
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                <i class="far fa-file-alt"></i>
                <span> Reports <i class="fas fa-angle-down"></i> </span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Daily Report</a>
                <a class="dropdown-item" href="#">Weekly Report</a>
                <a class="dropdown-item" href="#">Yearly Report</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% static 'admin/products.html' %}">
                <i class="fas fa-shopping-cart"></i> Products
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="accounts.html">
                <i class="far fa-user"></i> Accounts
              </a>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                <i class="fas fa-cog"></i>
                <span> Settings <i class="fas fa-angle-down"></i> </span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Profile</a>
                <a class="dropdown-item" href="#">Billing</a>
                <a class="dropdown-item" href="#">Customize</a>
              </div>
            </li>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link d-block" href="login.html">
                Admin, <b>Logout</b>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container tm-mt-big tm-mb-big">
      <div class="row">
        <div class="col-xl-9 col-lg-10 col-md-12 col-sm-12 mx-auto">
          <div class="tm-bg-primary-dark tm-block tm-block-h-auto">
            <div class="row">
              <div class="col-12">
                <h2 class="tm-block-title d-inline-block">Edit Product</h2>
              </div>
            </div>
            <div class="row tm-edit-product-row">
              <div class="col-xl-6 col-lg-6 col-md-12">
                <form action="" method="post" class="tm-edit-product-form">
                  <div class="form-group mb-3">
                    <label
                      for="name"
                      >Product Name
                    </label>
                    <input
                      id="name"
                      name="name"
                      type="text"
                      value="Lorem Ipsum Product"
                      class="form-control validate"
                    />
                  </div>
                  <div class="form-group mb-3">
                    <label
                      for="description"
                      >Description</label
                    >
                    <textarea                    
                      class="form-control validate tm-small"
                      rows="5"
                      required
                    >Lorem ipsum dolor amet gentrify glossier locavore messenger bag chillwave hashtag irony migas wolf kale chips small batch kogi direct trade shaman.</textarea>
                  </div>
                  <div class="form-group mb-3">
                    <label
                      for="category"
                      >Category</label
                    >
                    <select
                      class="custom-select tm-select-accounts"
                      id="category"
                    >
                      <option>Select category</option>
                      <option value="1" selected>New Arrival</option>
                      <option value="2">Most Popular</option>
                      <option value="3">Trending</option>
                    </select>
                  </div>
                  <div class="row">
                      <div class="form-group mb-3 col-xs-12 col-sm-6">
                          <label
                            for="expire_date"
                            >Expire Date
                          </label>
                          <input
                            id="expire_date"
                            name="expire_date"
                            type="text"
                            value="22 Oct, 2020"
                            class="form-control validate"
                            data-large-mode="true"
                          />
                        </div>
                        <div class="form-group mb-3 col-xs-12 col-sm-6">
                          <label
                            for="stock"
                            >Units In Stock
                          </label>
                          <input
                            id="stock"
                            name="stock"
                            type="text"
                            value="19,765"
                            class="form-control validate"
                          />
                        </div>
                  </div>
                  
              </div>
              <div class="col-xl-6 col-lg-6 col-md-12 mx-auto mb-4">
                <div class="tm-product-img-edit mx-auto">
                  <img src="img/product-image.jpg" alt="Product image" class="img-fluid d-block mx-auto">
                  <i
                    class="fas fa-cloud-upload-alt tm-upload-icon"
                    onclick="document.getElementById('fileInput').click();"
                  ></i>
                </div>
                <div class="custom-file mt-3 mb-3">
                  <input id="fileInput" type="file" style="display:none;" />
                  <input
                    type="button"
                    class="btn btn-primary btn-block mx-auto"
                    value="CHANGE IMAGE NOW"
                    onclick="document.getElementById('fileInput').click();"
                  />
                </div>
              </div>
              <div class="col-12">
                <button type="submit" class="btn btn-primary btn-block text-uppercase">Update Now</button>
              </div>
            </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <footer class="tm-footer row tm-mt-small">
        <div class="col-12 font-weight-light">
          <p class="text-center text-white mb-0 px-4 small">
            Copyright &copy; <b>2018</b> All rights reserved. 
            
            Design: <a rel="nofollow noopener" href="https://templatemo.com" class="tm-footer-link">Template Mo</a>
        </p>
        </div>
    </footer> 


    <script src="jquery-ui-datepicker/jquery-ui.min.js"></script>
    <!-- https://jqueryui.com/download/ -->

    <script>
      $(function() {
        $("#expire_date").datepicker({
          defaultDate: "10/22/2020"
        });
      });
    </script>


{% endblock %}

vrindavan_project/templates/adminfile/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Product Admin - Dashboard HTML Template</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
    <!-- https://fonts.google.com/specimen/Roboto -->
    <link rel="stylesheet" href="{% static 'adminfiles/css/fontawesome.min.css' %}">
    <!-- https://fontawesome.com/ -->
    <link rel="stylesheet" href="{% static 'adminfiles/css/bootstrap.min.css' %}">
    <!-- https://getbootstrap.com/ -->
    <link rel="stylesheet" href="{% static 'adminfiles/css/templatemo-style.css' %}">
    <!-- Product Admin CSS Template -->
</head>

<body>
    <div class="container tm-mt-big tm-mb-big">
        <div class="row">
            <div class="col-12 mx-auto tm-login-col">
                <div class="tm-bg-primary-dark tm-block tm-block-h-auto">
                    <div class="row">
                        <div class="col-12 text-center">
                            <h2 class="tm-block-title mb-4">Welcome to Dashboard, Login</h2>
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-12">
                            <form action="{% url 'adminlogin' %}" method="post" class="tm-login-form">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="username">Username</label>
                                    <input name="username" type="text" class="form-control validate" id="username" required />
                                </div>
                                <div class="form-group mt-3">
                                    <label for="password">Password</label>
                                    <input name="password" type="password" class="form-control validate" id="password" required />
                                </div>
                                <div class="form-group mt-4">
                                    <button type="submit" class="btn btn-primary btn-block text-uppercase">
                                        Login
                                    </button>
                                </div>
                                <a href="{% url 'password_reset' %}" class="mt-5 btn btn-primary btn-block text-uppercase">
                                    Forgot Password?
                                </a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="tm-footer row tm-mt-small">
        <div class="col-12 font-weight-light">
            <p class="text-center text-white mb-0 px-4 small">
                Copyright &copy; <b>2018</b> All rights reserved.
                Design: <a rel="nofollow noopener" href="https://templatemo.com" class="tm-footer-link">Template Mo</a>
            </p>
        </div>
    </footer>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

vrindavan_project/templates/adminfile/update_product.html
{% extends 'adminfile/ad_parent.html' %}
{% load static %}

{% block contents %}

<title>Update Product - Dashboard HTML Template</title>

<link rel="stylesheet" href="{% static 'jquery-ui-datepicker/jquery-ui.min.css' %}" type="text/css" />
<!-- http://api.jqueryui.com/datepicker/ -->

<div class="container tm-mt-big tm-mb-big">
  <div class="row">
      <div class="col-xl-9 col-lg-10 col-md-12 col-sm-12 mx-auto">
          <div class="tm-bg-primary-dark tm-block tm-block-h-auto">
              <div class="row">
                  <div class="col-12">
                      <h2 class="tm-block-title d-inline-block">Update Product</h2>
                  </div>
              </div>
              <div class="row tm-edit-product-row">
                  <div class="col-xl-6 col-lg-6 col-md-12">
                      <form method="post">
                          {% csrf_token %}
                          {{ form.as_p }}
                          <button type="submit" class="btn btn-primary btn-block text-uppercase">Save</button>
                      </form>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

<script src="{% static 'jquery-ui-datepicker/jquery-ui.min.js' %}"></script>
<!-- https://jqueryui.com/download/ -->

<script>
  $(function() {
    $("#expire_date").datepicker();
  });
</script>

{% endblock %}